"use client";
import { useEffect, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { X } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "./button";
export interface DialogProps { open: boolean; onClose: () => void; title: string; description?: string; children?: ReactNode; footer?: ReactNode; size?: "sm" | "md" | "lg"; }
export function Dialog({ open, onClose, title, description, children, footer, size = "md" }: DialogProps) {
  useEffect(() => { if (!open) return; const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); }; document.addEventListener("keydown", onKey); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", onKey); document.body.style.overflow = ""; }; }, [open, onClose]);
  if (!open) return null;
  return createPortal(<div className="fixed inset-0 z-[90] flex items-end justify-center sm:items-center"><button className="absolute inset-0 bg-black/45 backdrop-blur-sm" aria-label="Хаах" onClick={onClose} /><div role="dialog" aria-modal="true" aria-label={title} className={cn("safe-pb relative z-10 w-full rounded-t-3xl border border-zinc-200 bg-white shadow-2xl sm:rounded-2xl dark:border-white/10 dark:bg-zinc-900", size === "sm" && "sm:max-w-md", size === "md" && "sm:max-w-lg", size === "lg" && "sm:max-w-2xl")}><div className="mx-auto mt-3 h-1 w-9 rounded-full bg-zinc-300 sm:hidden dark:bg-white/20" /><div className="flex items-start justify-between gap-4 p-5 pb-2 sm:p-6 sm:pb-2"><div><h2 className="text-lg font-semibold tracking-tight text-zinc-950 dark:text-white">{title}</h2>{description ? <p className="mt-1 text-sm leading-6 text-zinc-500 dark:text-zinc-400">{description}</p> : null}</div><button onClick={onClose} aria-label="Хаах" className="rounded-xl p-2 text-zinc-500 transition hover:bg-zinc-100 hover:text-zinc-950 dark:hover:bg-white/10 dark:hover:text-white"><X className="h-5 w-5" /></button></div><div className="max-h-[70vh] overflow-y-auto p-5 pt-3 sm:p-6 sm:pt-3">{children}</div>{footer ? <div className="flex flex-col-reverse gap-2 border-t border-zinc-200 p-4 sm:flex-row sm:items-center sm:justify-end dark:border-white/10">{footer}</div> : null}</div></div>, document.body);
}
export interface ConfirmDialogProps { open: boolean; onClose: () => void; onConfirm: () => void | Promise<void>; title: string; description?: string; confirmLabel?: string; cancelLabel?: string; danger?: boolean; loading?: boolean; }
export function ConfirmDialog({ open, onClose, onConfirm, title, description, confirmLabel = "Тийм", cancelLabel = "Болих", danger, loading }: ConfirmDialogProps) { return <Dialog open={open} onClose={onClose} title={title} description={description} size="sm" footer={<><Button variant="ghost" onClick={onClose} disabled={loading}>{cancelLabel}</Button><Button variant={danger ? "danger" : "primary"} loading={loading} onClick={async () => { await onConfirm(); onClose(); }}>{confirmLabel}</Button></>} />; }
