"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { cn, formatMemberCount, formatTugrik } from "@/lib/utils";
export type StatFormat = "number" | "members" | "tugrik";
export function StatCard({ label, value, format = "number", icon, tone = "brand", hint }: { label: string; value: number; format?: StatFormat; icon?: ReactNode; tone?: "brand" | "gold" | "danger" | "info" | "neutral"; hint?: string; }) {
  const [display, setDisplay] = useState(0); const ref = useRef<HTMLDivElement>(null); const started = useRef(false);
  useEffect(() => { const el = ref.current; if (!el) return; const observer = new IntersectionObserver((entries) => { if (entries[0]?.isIntersecting && !started.current) { started.current = true; const duration = 700; const start = performance.now(); const tick = (now: number) => { const p = Math.min(1, (now - start) / duration); setDisplay(Math.round(value * (1 - Math.pow(1 - p, 3)))); if (p < 1) requestAnimationFrame(tick); }; requestAnimationFrame(tick); } }, { threshold: 0.3 }); observer.observe(el); return () => observer.disconnect(); }, [value]);
  const tones: Record<string, string> = { brand: "bg-zinc-100 text-zinc-700 dark:bg-white/10 dark:text-zinc-200", gold: "bg-amber-500/10 text-amber-700 dark:text-amber-300", danger: "bg-rose-500/10 text-rose-700 dark:text-rose-300", info: "bg-sky-500/10 text-sky-700 dark:text-sky-300", neutral: "bg-zinc-100 text-zinc-600 dark:bg-white/10 dark:text-zinc-300" };
  return <div ref={ref} className="rounded-2xl border border-zinc-200/80 bg-white p-5 shadow-[0_1px_2px_rgba(0,0,0,0.035)] dark:border-white/10 dark:bg-zinc-900 dark:shadow-none"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-zinc-500 dark:text-zinc-400">{label}</p>{icon ? <span className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-xl", tones[tone])}>{icon}</span> : null}</div><p className="mt-3 text-3xl font-bold tracking-tight tabular-nums text-zinc-950 dark:text-white">{format === "members" ? formatMemberCount(display) : format === "tugrik" ? formatTugrik(display) : display.toLocaleString("mn-MN")}</p>{hint ? <p className="mt-1 text-xs leading-5 text-zinc-500 dark:text-zinc-400">{hint}</p> : null}</div>;
}
