"use client";
import { createContext, useCallback, useContext, useRef, useState, type ReactNode } from "react";
import { CheckCircle2, AlertTriangle, Info, XCircle, X } from "lucide-react";
import { cn } from "@/lib/utils";
type ToastTone = "success" | "error" | "warning" | "info";
interface ToastItem { id: number; message: string; tone: ToastTone; }
interface ToastContextValue { toast: (message: string, tone?: ToastTone) => void; success: (message: string) => void; error: (message: string) => void; }
const ToastContext = createContext<ToastContextValue | null>(null);
export function useToast(): ToastContextValue { const ctx = useContext(ToastContext); if (!ctx) throw new Error("useToast нь ToastProvider дотор ашиглагдах ёстой"); return ctx; }
const icons: Record<ToastTone, ReactNode> = { success: <CheckCircle2 className="h-5 w-5 text-emerald-600 dark:text-emerald-400" />, error: <XCircle className="h-5 w-5 text-rose-600 dark:text-rose-400" />, warning: <AlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-400" />, info: <Info className="h-5 w-5 text-sky-600 dark:text-sky-400" /> };
export function ToastProvider({ children }: { children: ReactNode }) { const [toasts, setToasts] = useState<ToastItem[]>([]); const counter = useRef(0); const remove = useCallback((id: number) => setToasts((prev) => prev.filter((t) => t.id !== id)), []); const push = useCallback((message: string, tone: ToastTone) => { const id = ++counter.current; setToasts((prev) => [...prev.slice(-3), { id, message, tone }]); window.setTimeout(() => remove(id), 4200); }, [remove]); const toast = useCallback((message: string, tone: ToastTone = "info") => push(message, tone), [push]); const success = useCallback((message: string) => push(message, "success"), [push]); const error = useCallback((message: string) => push(message, "error"), [push]); return <ToastContext.Provider value={{ toast, success, error }}>{children}<div className="pointer-events-none fixed inset-x-0 top-4 z-[100] flex flex-col items-center gap-2 px-4 sm:items-end sm:pr-6">{toasts.map((t) => <div key={t.id} role="status" className={cn("pointer-events-auto flex w-full max-w-sm items-center gap-3 rounded-2xl border border-zinc-200 bg-white/95 px-4 py-3 shadow-xl backdrop-blur-xl dark:border-white/10 dark:bg-zinc-900/95")}>{icons[t.tone]}<p className="flex-1 text-sm font-medium leading-5 text-zinc-800 dark:text-zinc-100">{t.message}</p><button onClick={() => remove(t.id)} aria-label="Хаах" className="rounded-lg p-1 text-zinc-400 transition hover:bg-zinc-100 hover:text-zinc-950 dark:hover:bg-white/10 dark:hover:text-white"><X className="h-4 w-4" /></button></div>)}</div></ToastContext.Provider>; }
